HelloDjango/HelloDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('office.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

HelloDjango/office/urls.py
from django.urls import path
from . import views

app_name = 'office'
urlpatterns = [
    path('', views.sites, name='sites'),
    path('update_sites/', views.update_sites, name='update_sites'),
    path('get-title/<int:hard>/', views.get_site_title, name='get_site_title'),
    path('old-lands', views.old_lands, name='old_lands'),
    path('requisites', views.requisites, name='requisites'),
    # path('checker/<int:site_id>/<str:mode>/', views.checker, name='checker'),
    path('checker/<int:site_id>/<int:mode>/', views.checker, name='checker'),
    path('domains', views.domains, name='domains'),
    path('domains/<int:dom_id>/<str:source>/<str:new_status>/', views.domain_change_status, name='change_status'),
    path('campanings/', views.campanings, name='campanings'),
    path('delete_site/<int:site_id>/', views.delete_site, name='del_site'),
    path('api/', views.domains_list_api),
    path('api/campanings/', views.company_list_api),
    path('api/campaning_detail/<int:pk>/', views.campaning_detail),
    path('api/change_domain_desc/<int:pk>/', views.domains_detail),
    path('api/zapusk/', views.zapusk_data),
    path('api/create_capmaning/', views.create_capmaning),
    path('api/add_lead/', views.add_lead),
    path('leads/', views.all_leads, name='leads'),
    path('main/', views.main, name='main'),
    path('update_leads/', views.update_leads, name='update_leads'),
    ]

HelloDjango/office/views.py
import requests
import json
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from rest_framework import status
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from pprint import pprint
from .api import Beget, TrirazatApi
from .help import ImagePrev
from .link_checker import LinkCheckerManager
from .models import Site, OldLand, Domain, CodeExample, Company, Account, CampaignStatus, TrafficSource, Cabinet,\
    Country, Lead, RootDomain, SubDomain
from .serializers import DomainSerializer, CompanySerializer, AccountSerializer, TrafficSourceSerializer,\
    CabinetSerializer, CountrySerializer, LeadSerializer
from .new_checker import SiteMap as SiteMap, LinkChecker as NewLinkChecker
from django.views.decorators.csrf import csrf_exempt


DJANGO_SITE = 'https://main-prosale.store/'
NO_CONNECTION = 'Не удалось подключиться'


def main(request):
    return render(request, 'office/index_test.html')


@login_required
def sites(request):
    """Список сайтов, их статусов и тд"""
    # res = Company.objects.exclude(status_name__not="Запущено")
    # print(len(res), 'xxxxxxxxxxxxx')
    # sites = Site.objects.all().order_by('-pk')
    sites = list(Site.objects.exclude(site_name__in=Site.DONT_CHECK))  # исключаються тех сайты
    sites.sort(key=Site.get_sort_name)
    content = {'sites': sites,
               'page_title': 'Сайты',
               }
    return render(request, 'office/index.html', content)


@login_required
def update_sites(request):
    """Обновить список сайтов"""
    # TODO при изменение домена, если можель уже существует - домены не обновяться
    b = Beget()
    sites_id_bd = set([site.beget_id for site in Site.objects.all()])
    sites_beget = b.get_sites()
    sites_beget_id = set([site['id'] for site in sites_beget])
    sites_to_del = sites_id_bd - sites_beget_id
    # сайтов из базы которых нет в ответе с сервера
    for site_beget_id in sites_to_del:
        s = Site.objects.get(beget_id=site_beget_id)
        s.delete()
    for site_beget in sites_beget:
        try:
            site = Site.objects.get(beget_id=site_beget['id'])
        except Site.DoesNotExist:
            # добавление нового сайта
            beget_id = site_beget['id']
            site_name = site_beget['path']
            site = Site(beget_id=beget_id, site_name=site_name, title='None')
            site.save()
            site.check_cloac()
            site.update_title()
        # обновление доменов сайта
        for domain in site_beget['domains']:
            domain_beget_id = domain['id']
            try:
                domain = Domain.objects.get(beget_id=domain_beget_id)
            except ObjectDoesNotExist:
                b.update_domains()
                domain = Domain.objects.get(beget_id=domain_beget_id)
            site.domain_set.add(domain)
        site.save()
    return HttpResponseRedirect(reverse('office:sites'))


@login_required
def get_site_title(request, hard):
    # TODO удалить - перенести в Page
    """Обновить заголовки сайтов"""
    for site in Site.objects.all():
        site.update_title(bool(hard))
        # site.save()
    return HttpResponseRedirect(reverse('office:sites'))


@login_required
def old_lands(request):
    """Архив старых лэндов"""
    host = request.get_host()
    DOMAIN = 'http://vladiuse.beget.tech/'
    SOURCE_URL = 'http://vladiuse.beget.tech/get_lands_list.php'
    res = requests.get(SOURCE_URL)
    lands = res.text.split(';')
    if not lands[-1]:
        lands = lands[:-1]
    old_lands = OldLand.objects.all()
    old_lands_name = [old.name for old in old_lands]
    to_add = set(lands) - set(old_lands_name)
    to_dell = set(old_lands_name) - set(lands)
    for name in to_add:
        url = DOMAIN + name
        image = ImagePrev(url=url, name=name, host=host).get_image()
        old_dom = OldLand(name=name, url=url, image=image)
        old_dom.save()
    for name in to_dell:
        dom = OldLand.objects.get(name=name)
        dom.delete()
    old_lands = OldLand.objects.all()
    land_count = len(old_lands)
    info = f'Новых: {len(to_add)}, удалено: {len(to_dell)}'
    content = {
        'land_count': land_count,
        'domain': DOMAIN,
        'old_lands': old_lands,
        'info': info,
        'page_title': 'Архив',
    }
    return render(request, 'office/old_lands.html', content)


@login_required
def requisites(request):
    """Реквизиты и шаблоны html, css, js"""
    examples = CodeExample.objects.all()
    content = {
        'examples': examples,
        'page_title': 'Реквизиты',
    }
    return render(request, 'office/requisites.html', content)


@login_required
def checker(request, site_id, mode):
    """Проверочник сайтов"""
    site_model = Site.objects.get(pk=site_id)
    is_check_start = ''
    if not (mode == 0 and site_model.check_status != 'Не проверен'):
        # с главной страницы
        url = site_model.get_http_site()
        site_dir = site_model.site_name + '/public_html'
        site = SiteMap(url=url, is_cloac=site_model.is_cloac, dir_name=site_dir)
        checker = NewLinkChecker(site=site)
        checker.process()
        site_model.check_status = checker.result['result_text']
        new_check_data = {'main': checker.result,
                          'checkers': checker.results_from_checkers,}
        site_model.check_data = new_check_data
        site_model.save()
        is_check_start = 'Выполнена загрузка'
    content = {
        'site': site_model,
        'data': site_model.check_data,
        'is_check_start': is_check_start,
        'page_title': 'Проверка',
    }
    return render(request, 'office/checker.html', content)

@login_required
def domains(request):
    """Список доменов"""
    Beget().update_domains()
    domains_bd = RootDomain.objects.exclude(is_full=True).order_by('name')
    # domains_bd = [domain for domain in domains_bd if domain.is_root() is True]
    # for dom in domains_bd:
    #     print(dom.name, dom.is_root())
    # free_doms = Domain.objects.filter(site__isnull=True)
    content = {'domains': domains_bd,
               # 'free_doms': free_doms,
               'page_title': 'Домены',
               }
    return render(request, 'office/domains.html', content)


@login_required
def domain_change_status(request, dom_id, source, new_status):
    """Изменение статуса домена"""
    s = {
        'BAN': Domain.BAN,
        'USE': Domain.USE,
        'NEW': Domain.NEW,
    }
    new_status = s[new_status]
    domain = Domain.objects.get(pk=dom_id)
    if source == 'facebook':
        domain.facebook = new_status
    elif source == 'google':
        domain.google = new_status
    elif source == 'tiktok':
        domain.tiktok = new_status
    else:
        pass
    domain.save()
    return HttpResponseRedirect(reverse('office:domains'))

@login_required
def delete_site(request, site_id):
    site = Site.objects.get(pk=site_id)
    b = Beget()
    result = b.del_site(site.beget_id)
    if result:
        site.delete()
    return JsonResponse({'answer': result})


@login_required
@api_view(['GET', 'POST'])
@renderer_classes([JSONRenderer])
def domains_list_api(request):
    if request.method == 'GET':
        domains = Domain.objects.all()
        domains = [domain for domain in domains if domain.is_root() is True]
        serializer = DomainSerializer(domains, many=True)
        return Response(serializer.data)


@login_required
@api_view(['GET', 'POST'])
@renderer_classes([JSONRenderer])
def domains_detail(request, pk):
    try:
        domain = Domain.objects.get(pk=pk)
    except Domain.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = DomainSerializer(domain)
        return Response(serializer.data, )
    elif request.method == 'POST':
        serializer = DomainSerializer(domain, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@login_required
@api_view(['GET'])
@renderer_classes([JSONRenderer])
def company_list_api(request):
    companys = Company.objects.all()
    serializer = CompanySerializer(companys, many=True)
    return Response(serializer.data)


@login_required
@api_view(['GET', 'POST'])
@renderer_classes([JSONRenderer])
def campaning_detail(request, pk):
    """ получения данных по РК или обновление"""
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CompanySerializer(company)
        return Response(serializer.data, )
    elif request.method == 'POST':
        print(request.data, )
        serializer = CompanySerializer(company)

        CompanySerializer().update(company, request.data)
        # if serializer.is_valid():
        #     serializer.save()
        #     print('good')
        return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@login_required
@api_view(['GET', 'POST'])
@renderer_classes([JSONRenderer])
def create_capmaning(request):
    """Создание новой кампании"""
    # TODO - при создании кампании сайт - не становиться запущеным!
    data = json.loads(request.POST['data'])
    name = data['text']
    pixel = data['pixel']
    daily = data['daily']
    cab = Cabinet.objects.get(pk=data['cab_id'])
    status = CampaignStatus.objects.get(pk=5)
    new_camp = Company(name=name, cab=cab, status=status, daily=daily, pixel=pixel)
    new_camp.save()
    for geo_id in data['geos_id']:
        country = Country.objects.get(pk=geo_id)

HelloDjango/office/templates/office/base.html
{% load static %}
<h1 style="display: none">Django</h1>
<!-- css -->
<!-- <link rel="stylesheet" href="{% static 'office/bootstrap.min.css' %}"> -->
<link rel="stylesheet" href="{% static 'office/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'office/styles.css' %}">
<link rel="stylesheet" href="{% static 'office/flag-icon.min.css' %}">
<!-- js -->
<script src="{% static 'office/jq.js' %}"></script>
<script src="{% static 'office/popper.min.js' %}"></script>
<!-- <script src="{% static 'office/bootstrap.bundle.js' %}"></script> -->
<script src="{% static 'office/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'office/main.js' %}"></script>

<!--ICONS-->
<script src="https://kit.fontawesome.com/0960a95ef5.js" crossorigin="anonymous"></script>


<!-- НАчало сайта -->
<head>
<!-- <title>Django</title> -->

<!--  <link rel="shortcut icon" href="{% static 'office/favicon.svg' %}" type="image/svg">-->
</head>
<body>

    
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        
        <div class="container-fluid">
          
          <!-- <a class="navbar-brand" href="#">
          </a> -->
          <a class="navbar-brand  h5"  href="#" id="site_logo"><span style="color:#20aa76;">D</span>JANGO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse clearfix" id="navbarNavDropdown">
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'office:sites' %}">Сайты</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'office:campanings' %}">Кампании</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'office:domains' %}">Домены</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'office:leads' %}">Лиды</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'office:requisites' %}">Реквизиты</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Обновить
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'office:update_sites' %}">Список сайтов</a></li>
                  <li><a class="dropdown-item" href="{% url 'office:get_site_title' 0 %}">Заголовки сайтов</a></li>
                  <li><a class="dropdown-item" href="{% url 'office:get_site_title' 1 %}">Заголовки сайтов(все)</a></li>
                </ul>
              </li> -->

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Ссылки
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="https://cp.beget.com/sites" target="_blank">Сайты</a></li>
                  <li><a class="dropdown-item" href="https://cp.beget.com/domains" target="_blank">Домены</a></li>
                  <!-- <li><a class="dropdown-item" href="{% url 'office:old_lands' %}" target="_blank">Архив прокл</a></li> -->
                  <li><a class="dropdown-item" href="/admin">Admin</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown login" >
                <a class="nav-link dropdown-toggle" ata-bs-display="static" href="#" id="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username  }}
                </a>
                <ul class="dropdown-menu position-sticky dropdown-menu-dark"  aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="#">Информация</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
                </ul>
                   
              </li>
              {% else %}
              <style>
                #navbarNavDropdown{
                  flex-grow: 0;
                }
              </style>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'login' %}">Войти</a>
              </li>
              {% endif %}
            </ul>
            
          </div>
         
          <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
            <ul class="navbar-nav ">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown" >
                <a class="nav-link dropdown-toggle" ata-bs-display="static" href="#" id="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  User
                </a>
                <ul class="dropdown-menu dropdown-menu-sm-start"  aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
                  <li><a class="dropdown-item" href="#">Информация</a></li>
                </ul>
                
                {% else %}
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Войти</a>
              </li>
              {% endif %}
            </ul>
          
          </nav> -->
        </div>
     
      </nav>
<!-- <script>
  $('nav a').click(function(){
  $('nav ul').removeClass('show')
  })
</script> -->


{% block content %}
{% endblock %}
<!-- </body>
</html> -->

HelloDjango/office/templates/office/camp.html
<tr id="{{ comp.id }}">         
            
  <td class="{{comp.cab.account.source.short_name}}"><div class="icon-block"><code>{{ comp.cab.account.source.icon_html|safe  }}</code></div>
      <!-- {{ comp.cab.account.source.name }} -->
  </td>
  <!-- <td></td> -->
  <td>{{ comp.cab.account.name }}: {{ comp.cab }}</td>
  <td>
      {% for geo in comp.geo.all %}
      <a data-bs-toggle="tooltip" data-bs-placement="left" title="{{geo.name_ru}}">
        <span class="flag-icon flag-icon-{{geo.short_name}} flag-icon-squared"></span></a>
      
      <!-- {{ geo.short_name}} -->
      {% endfor %}
  </td>
<!--            <td>{{comp.get_comp_id}}</td>-->
  <td class="pixel-block">
   <!-- Pxilex -->
   {% if comp.is_comp_active %}
   {% if comp.is_pixel_correct %}
   <i class="fas fa-check-circle"></i>
   {% endif %}
   {% endif %}
   {{ comp.pixel }}
  </td>
  <td>{% if comp.daily %}{{comp.daily}}{% endif %}</td>
  <td>{{ comp.name }}</td>
  <td>
      {% for land in comp.land.all %}
      <!-- {{ geo.name}} -->

<a data-bs-toggle="tooltip" data-bs-placement="left" title="{{ land.site.check_status}}">{{ land.name}}</a>
      <!-- {{ geo.name}}{{ geo.site.check_status}}<br> -->
      {% endfor %}
  </td>
  <td class="camp-status">
      <!-- status -->
      <div class="dropdown">
          <button class="btn dropdown-toggle" type="button" id="" data-bs-toggle="dropdown" current-status="{{comp.status.id}}"  aria-expanded="false">{{ comp.status }}</button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              {% for status in statusys %}
            <li><a class="dropdown-item" camp-status="{{status.id}}" current-status="{{comp.status.id}}">{{ status.name }}</a></li>
              {% endfor %}
          </ul>
        </div>
       <!-- status -->
  </td>
  <td>
    <!-- Прочее -->
    <div class="dropdown">
      <button type="button" class="btn btn-light dropdown-toggle icon-block"  data-bs-toggle="dropdown" data-bs-target="#exampleModal">
          <i class="fas fa-cogs "></i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="/admin/office/company/{{comp.id}}/change/" target="_blank">Редактировать</a></li>
          <!-- <li><a class="dropdown-item" href="" target="_blank">---</a></li> -->
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item disabled" href="#" data-bs-toggle="modal" data-bs-target="#">Удалить</a></li>                      
        </ul>
      </div>
  </td>
</tr>

HelloDjango/office/templates/office/checker.html
{% extends 'office/base.html' %}
{% block content %}
<title>{{ page_title }}</title>
<!--<h1>Checker</h1>-->
<!--{% if exception %}-->
<!--{{ exception }}-->
<!--{% endif %}-->

<!--<h3 class="{{ site.get_status_html }}">{{ site.check_status }}</h3>-->
<!--<a href="{{ site.domain }}">{{ site.domain }}</a>-->
<!--<br>-->
<!--    <table>-->
<!--        <thead>-->
<!--            <tr>-->
<!--                <th>Поле</th>-->
<!--                <th>Статус</th>-->
<!--            </tr>-->
<!--        </thead>-->
<!--     {% for key, value in content.items %}-->
<!--            <tr>-->
<!--                <td>{{ key }}</a></td>-->
<!--                <td><p class="{{ value.status }} status" >{{ value.info }}</p></td>-->
<!--            </tr>-->
<!--        {% endfor %}-->
<!--    </table>-->
<!-- <style>
    #update {
        color: green;
    }
</style> -->
<div class="main-wrapper">
<h3>
    <!-- <span class="mb-2 bg-{{data.main.result_html}}"> -->
        {{ data.main.result_text }}
    <!-- </span> -->
    : {{ site.title| slice:":30" }}
</h3>
<div class="icon-block">
    Проверяемый сайт: <a href="{{ site.get_http_site }}" target="_blank">{{ site.site_name }}</a>
    <a href="{{ site.get_beget_editor }}" target="_blank"><i class="fas fa-user-edit"></i></a>
    {% if site.is_cloac %}
                    <a href="{{ site.black_page }}" target="_blank"><i class="fas fa-user-secret"></i></a>
                    {% endif %}
</div>


<a class="btn btn-dark" role="button" href="{% url 'office:checker' site.id 1 %}">Обновить <i class="fas fa-cloud-download-alt"></i></a>
<br> {{ is_check_start }}

    <table class="table" style="margin-top: 10px;">
        <thead class="table-light">
        <tr>
            <!-- <th>Класс проверочник</th> -->
            <th>Описание</th>
            <th>Код</th>
            <th>Инфо</th>
            <th>Ошибки</th>
            
            <th>Текст</th>
        </tr>
        </thead>
        <tbody>
        {% for checker in data.checkers %}
        <tr >
            <!-- <td>{{ checker.name }}</td> -->
            <td>{{ checker.description }}</td>
            <td class="mb-2 bg-{{ checker.status_html }}">
                {{ checker.status_text }}
            </td>
            <td>{% for info in checker.info %}
                {{ info }}<br>
                {% endfor %}
            </td>
            <td>
                {% for error in checker.errors %}
                {{ error }}<br>
                {% endfor %}
            </td>
            <td>{% if checker.result_value %}
                {{ checker.result_value }}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>




</div>
{% endblock %}

HelloDjango/office/templates/office/index_test.html
{% extends 'office/base.html' %}
{% load static %}
{% block content %}
<style>
#pulp-wrapper {
    text-align: center;
    height: 100%;
    display: flex;
    justify-content: center;
    background-color: black;
}
    #pulp {
    width: 80%;
    margin: auto;
    }
</style>
<div id="pulp-wrapper">
    <img src="{% static 'office/pulp.jpg' %}" alt="pulp" id="pulp">
</div>
{% endblock %}

HelloDjango/office/templates/office/leads.html
{% extends 'office/base.html' %}
{% block content %}
<title>{{ page_title }}</title>
<style>
    .leads-table{
        font-size: 14px;
    }
</style>

<div class="main-wrapper">
    <h6>{{update_count}}</h6>
<a href="{% url 'office:update_leads' %}">Update</a>
    <table class="table leads-table">
        <thead class="table-light">
            <tr>
                <!-- <th>Id</th> -->
                <th>ПП</th>
                 <th>Имя</th>
                 <th>Телефон</th>
                 <th>Страна</th>
                 <th>Комм</th>
                 <th>Цена</th>
                 <th>Оффер</th>
                <th>Поток</th>
                <th>Id Лида</th>
                <th>Домен</th>
                <th>Ответ</th>
<!--                <th>Data</th>-->
                                <th>Status</th>
                <th>Дата</th>
            </tr>
        </thead>
        <tbody>
        {% for lead in leads %}
        <tr>
            <!-- <td>{{ lead.id }}</td> -->
            <td>{{ lead.pp_name|default_if_none:"" }}</td>
            <td>{{ lead.name|default_if_none:"" }}</td>
            <td>{{ lead.phone|default_if_none:"" }}</td>
            <td>{{ lead.country|default_if_none:"" }}</td>
            <td>{{ lead.comm|default_if_none:"" }}</td>
            <td>{{ lead.price|default_if_none:"" }}</td>
            <td>{{ lead.offer_id|default_if_none:"" }}</td>
            <td>{{ lead.flow_id|default_if_none:"" }}</td>
            <td>{{ lead.lead_id|default_if_none:"" }}</td>
            <td>{{ lead.domain|default_if_none:"" }}</td>
            <td>{{ lead.pp_answer|default_if_none:"" }}</td>
<!--            <td>{{lead.pp_lead_status}}</td>-->
                        <td style="color: {{lead.get_status_color}};">{{lead.get_status_icon|safe}} {{ lead.get_lead_status_word_ru }}</td>
            <td>{{ lead.created|date:'m.d H:i' }}</td>
        </tr>
         {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}